"""initial_schema

Revision ID: 66e2d97abc85
Revises: 
Create Date: 2026-09-30 02:58:32.187478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66e2d97abc85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_structure', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_table('export_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('test_case_count', sa.Integer(), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_history_project_id', 'export_history', ['project_id'], unique=False)
    op.create_table('extracted_contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('business_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('state_changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('dependencies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ambiguities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('ix_extracted_contexts_project_id', 'extracted_contexts', ['project_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('roles_involved', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'project_id')
    )
    op.create_index('ix_requirements_project_id', 'requirements', ['project_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=50), nullable=True),
    sa.Column('business_rule_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('scenario_type', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('preconditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('test_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'project_id')
    )
    op.create_index('ix_test_cases_project_req', 'test_cases', ['project_id', 'requirement_id'], unique=False)
    op.create_index('ix_test_cases_project_status', 'test_cases', ['project_id', 'status'], unique=False)
    op.create_table('flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggested_question', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id', 'project_id'], ['test_cases.id', 'test_cases.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flags_project_tc', 'flags', ['project_id', 'test_case_id'], unique=False)
    op.create_table('test_case_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('change_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id', 'project_id'], ['test_cases.id', 'test_cases.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_case_versions_lookup', 'test_case_versions', ['project_id', 'test_case_id', 'version_number'], unique=False)
    
    # Supabase PostgREST Data API protection:
    # Ensure application tables are not publicly accessible through PostgREST.
    # Enable RLS with no public policies, and revoke all grants from anon/authenticated roles.
    # FastAPI connects server-side via direct/service role which retains full access.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for table in [
            'projects',
            'extracted_contexts',
            'requirements',
            'test_cases',
            'test_case_versions',
            'flags',
            'export_history'
        ]:
            op.execute(sa.text(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;"))
            op.execute(sa.text(f"REVOKE ALL ON TABLE {table} FROM anon, authenticated;"))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_case_versions_lookup', table_name='test_case_versions')
    op.drop_table('test_case_versions')
    op.drop_index('ix_flags_project_tc', table_name='flags')
    op.drop_table('flags')
    op.drop_index('ix_test_cases_project_status', table_name='test_cases')
    op.drop_index('ix_test_cases_project_req', table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index('ix_requirements_project_id', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('ix_extracted_contexts_project_id', table_name='extracted_contexts')
    op.drop_table('extracted_contexts')
    op.drop_index('ix_export_history_project_id', table_name='export_history')
    op.drop_table('export_history')
    op.drop_index('ix_projects_created_at', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
